name: build-release

on:
  push:
    branches: [ mainline ]
  pull_request:
    branches: [ mainline ]

jobs:

  build:
    runs-on: centos
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Install Deps
      run: |
        yum install -y rpm-build
    - name: Build
      run: make build-release
